### ISSUE TITLE
Addition of a status endpoint

### ISSUE THREAD

**Issue by josephdenne** [dadi/cdn#11]
A new endpoint at /status would enable a finer-grained approach to platform monitoring; would enable us make decisions relating to load (e.g. at load balancer level) on the basis of much more than just whether or not an CDN instance is responding to ping on port 80; and would allow us to more easily visualise stack performance.

/status would ideally return:

- An overall health indicator (green/amber/red)
- Messaging relating to the health indicator
- Provide CPU load and load averages
- Provide memory utilisation as well as free and freeable memory
- Provide uptime
- Provide the version of DADI CDN being used
- Alert where new version(s) are available

/status should be authenticated (using the same keys as used for the invalidation API), and also optional (enabled by default). The port for /status should also be configurable.

**Comment by adamkdean** [comment]
I've cribbed the `/api/status` endpoint handler from [dadi/api](https://github.com/dadi/api/blob/master/dadi/lib/index.js#L296) which uses [dadi/status](https://github.com/dadi/status) which gives us: 

- Provide CPU load and load averages ✓
- Provide memory utilisation ✓ as well as free ✓ and freeable memory ✘
- Provide uptime ✓
- Provide the version of DADI CDN being used ✓

Re: freeable memory, would this refer to free memory -/+ buffers/cache etc? Perhaps this would be something to put into [dadi/status](https://github.com/dadi/status) rather than the CDN directly. Would need to handle OS X differently given how macs wire memory.

For the `overall health indicator (green/amber/red)` and `messaging relating to the health indicator`, what would the criteria be for green/amber/red? Green – it's working, amber – it's working but slowly, red – it's kaput?

Poke 👉  @jimlambie

**Comment by jimlambie** [comment]
the status module allows for specifying routes and expected response times. For example `/index` should respond in 200ms or less. 

For CDN, perhaps we have a sample image in the app which we can hit - and then yes:

* green - response time faster than expected
* amber - response time slower than expected 
* red - no response? or VERY slooooow?

**Comment by adamkdean** [comment]
Good idea. I've added the following messaging:

    message: data.routes[0].healthStatus === 'Green'
      ? 'Service is responding within specified parameters'
      : data.routes[0].healthStatus === 'Amber'
        ? 'Service is responding, but outside of specified parameters'
        : 'Service is not responding correctly'

Green is within `expectedResponseTime`, amber is still responding but outside of `expectedResponseTime` and red is a bad response, such as a 404. I think there may be an [issue with dadi/status](https://github.com/dadi/status/blob/master/dadi/lib/index.js#L48) where a failure to connect results in certified Bad Times: `TypeError: Cannot read property 'statusCode' of undefined`.

**Comment by mingard** [comment]
Why not allow expandability:

```JS
message: statusMessage(data.routes[0].healthStatus)

var statusMessage = function(status) {
  switch(status) {
    case 'Green': 
      return 'Service is responding within specified parameters'
    break;
    case 'Amber':
      return 'Service is responding, but outside of specified parameters'
    break;
    default: 
      return 'Service is not responding correctly'
  }
}
```

Or:

```JS

var responseMessages: {
  Green: 'Service is responding within specified parameters',
  Amber: 'Service is responding, but outside of specified parameters'
}

var message: responseMessages[data.routes[0].healthStatus] || 'Service is not responding correctly'
```

**Comment by jimlambie** [comment]
It's not a huge problem, as the messaging will be done at another level, by the service that consumes this endpoint. That said, I am happy for this to be included, so don't remove it @adamkdean, or extend it as @mingard suggests.

Jim out.

**Comment by jimlambie** [comment]
Am I right in thinking you still return the colour?

```
{
  healthStatus: 'Green',
  message: 'All good, bro!'
}
```

**Comment by adamkdean** [comment]
Good idea, @mingard, but will leave this as instructed. 

@jimlambie Yes, status, healthStatus, and message: https://github.com/dadi/cdn/blob/5b8ee5e12e6c66745a1cc7d6453260c055251d3b/dadi/lib/index.js#L62

Note that the routes are still returned as standard dadi/status operation, but that I just grab a bit of it for a summary and pop that into `status`.

**Comment by adamkdean** [comment]
Acceptance tests and a fix in this PR: https://github.com/dadi/cdn/pull/44.

I think we can consider this closed once that is merged.
