### ISSUE TITLE
Standalone generator of responsive images with art direction

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/cdn#123]
It would be interesting to create a standalone web app to showcase CDN features, more specifically on-the-fly crop generation and the content-aware cropping mode.

People would be able to upload an image, select the breakpoints they want and the tool would generate all the necessary markup ([this pen](http://codepen.io/eduardoboucas/pen/ZOApOK) being an example of what could be generated).

References:
- http://www.responsivebreakpoints.com/
- https://www.smashingmagazine.com/2016/09/automating-art-direction-with-the-responsive-image-breakpoints-generator/

**Comment by jimlambie** [comment]
@eduardoboucas @abovebored could this be integrated into the docs? we'll have cdn.somedomain.tech running for other interactive parts...

**Comment by abovebored** [comment]
I'm working on this here - https://github.com/dadi/dadi.tech/issues/56

Will ping you guys for feedback as and when 🙏

**Comment by eduardoboucas** [comment]
I think this was done, at least partially, in the Sandbox app. Should we close the issue? 🔫
