### ISSUE TITLE
External image load

### ISSUE THREAD

**Issue by jimlambie** [dadi/cdn#151]
CDN currently handles retrieving assets from disk, S3 and a configurable remote server. A very useful addition would be to allow requesting publicly available images via CDN, where they could be processed and cached.

There is already an `http` storage module which is used for the remote server, so perhaps all we need is an extension to determine that a request is for an external image.

**Comment by jimlambie** [comment]
@eduardoboucas can you please pull branch 1.7.0-rc.1 and test this? thanks!

**Comment by eduardoboucas** [comment]
@jimlambie This is working like a charm. The reason why I was getting an error before is that I'm an idiot. 👍
