### ISSUE TITLE
Images won't load if no query is supplied

### ISSUE THREAD

**Issue by josephdenne** [dadi/cdn#160]
There are a few cases where no quality or size is required. Can we enable image loading in these cases (assuming that the image is within security thresholds)?

**Comment by eduardoboucas** [comment]
I've fixed this and it's currently in a branch that @jimlambie will release soon, if I'm not mistaken.

**Comment by jimlambie** [comment]
@eduardoboucas can you please pull branch 1.7.0-rc.1 and test this?

**Comment by eduardoboucas** [comment]
I can confirm this is working on the `1.7.0-rc.1` branch.
