### ISSUE TITLE
Signed URL support

### ISSUE THREAD

**Issue by josephdenne** [dadi/cdn#162]
The addition of support for signed URLs to enable the access of private assets in S3.

**Comment by jimlambie** [comment]
@josephdenne we already sign requests implicitly when initialising the S3 storage module:

```
AWS.config.update({ accessKeyId: 'AKID', secretAccessKey: 'SECRET' })
```

**Comment by josephdenne** [comment]
This is about being able to access pre-signed - as in limited timed access - URLs on S3. It's different to full bucket access.

See: http://docs.aws.amazon.com/aws-sdk-php/v2/api/class-Aws.S3.S3Client.html#_createPresignedUrl

**Comment by jimlambie** [comment]
Right, so we don't need to generate signed URLs ourselves, only use them.

**Comment by jimlambie** [comment]
This is closed by https://github.com/dadi/cdn/pull/225.

To be released to NPM later today (21/03/2017)
