### ISSUE TITLE
SSL handling

### ISSUE THREAD

**Issue by adamkdean** [dadi/cdn#165]
> X-Post from: https://github.com/dadi/web/issues/99

At the moment configuration appears to enable SSL as being either on or off. SSL needs to be supported in a variety of configurations:

- Just SSL
- SSL, with support for routing traffic from HTTP to HTTPS
- HTTPS alongside HTTP (either/or support)

In addition the method of recognising/enforcing an SSL request needs attention. In a load balanced setup the load balancer will usually handle SSL, piping requests as HTTP to the end instances.

**Comment by jimlambie** [comment]
Closed by f6120a643dfa64ec91dd9711ba5693c99d6a2411
