### ISSUE TITLE
Quality change ignored when reformatting PNG as JPG

### ISSUE THREAD

**Issue by mingard** [dadi/cdn#177]
When you simultaneously change the format of a *PNG* to *JPG* and applying a quality change, the output remains full quality. 

This means there is no way to change from lossless to lossy and degrade the quality.

I may be able to take a look at this shortly @jimlambie

**Comment by jimlambie** [comment]
Can you give me the URL parameters you used, or the full URL including image path, @mingard

**Comment by mingard** [comment]
@jimlambie http://mediatest.planetradio.co.uk/l/30/99e0b/8f14b/dd5c6/bb58c/0a328/bcf1d/simondogs.png?quality=10&format=jpg

**Comment by jimlambie** [comment]
@mingard got it, problem discovered, fixing
