### ISSUE TITLE
postinstall script fails if development config is not present

### ISSUE THREAD

**Issue by fra967** [dadi/cdn#230]
if `/dadi/client/cdn/config/config.development.json` is not present, installation fails

```
/dadi/client/cdn/node_modules/@dadi/cdn/scripts/copy-config.js:22
          if (err) throw err
                   ^

Error: EACCES: permission denied, open '/dadi/client/cdn/config/config.development.json'
    at Error (native)
```

CDN version 1.11.0

**Comment by jimlambie** [comment]
What are the permissions on the install directory? Does it allow creation of a new folder and/or file?

**Comment by fra967** [comment]
ok it seems that write permissions need to be given to the ubuntu user, even when npm install is run as root
