### ISSUE TITLE
Proposed new URL Syntax

### ISSUE THREAD

**Issue by dark12222000** [dadi/cdn#25]
The current path based syntax for working with images is very fragile. Adding, removing or modifying parameters will instantly break all clients using the CDN. I therefore would like to propose a new url structure based primarily on query values.

`mycdn/{storage_adapter}/{image_path}?{operation}={value}`

So for instance, `media.whatcar.com/s3/wc/reviews/porsche911.jpg?cropX=600&cropY=400`

In addition with the potential of switching to `libgd`,  #16  we could pair the new image processing library to the new syntax. Clients can then change at their own pace instead of being forced to update.

**Comment by jimlambie** [comment]
Closed by aae39e5a41fbd5e034000c8fe6e6f9ad45a505f1
