### ISSUE TITLE
Front end libraries

### ISSUE THREAD

**Issue by abovedave** [dadi/cdn#251]
Similar to [Cloudinary](http://cloudinary.com/), we could have front-end libraries to work with CDN. E.g.,

```php
Cloudinary::cloudinary_url("sample.jpg", array("width"=>300, "height"=>100, "crop"=>"scale", "secure"=>true))
```

```javascript
cloudinary.url("sample.jpg", {width: 300, height: 100, crop: "scale", secure: true})
```

etc

**Comment by eduardoboucas** [comment]
💯

However, I don't think this should live in the CDN repo, so I'm closing this. Maybe it lives in the docs site until we have a significant number of resources, or maybe it lives in the [registry](https://github.com/dadi/registry).
