### ISSUE TITLE
LastModified not provided when image served from cache

### ISSUE THREAD

**Issue by jimlambie** [dadi/cdn#253]
When an image is retrieved from either S3 or the filesystem, a LastModified header is added to the response, but when the cached version of the image is retrieved no LastModified header is added to the response (or `null` is returned)

**Comment by eduardoboucas** [comment]
Currently, the caching mechanism is simply a map between keys and streams - when we find a key that matches the request, we simply return the stream.

I think this issue should involve a wider discussion about whether CDN should have an internal database that could store metadata about cached items. This could be the last modified data, but could also be extended to other data.

**Comment by eduardoboucas** [comment]
> I think this issue should involve a wider discussion about whether CDN should have an internal database that could store metadata about cached items. This could be the last modified data, but could also be extended to other data.

And here it is: https://github.com/dadi/cache/issues/24. Until that's done, this issue is blocked. 🚫
