### ISSUE TITLE
GIF support

### ISSUE THREAD

**Issue by jimlambie** [dadi/cdn#257]
With the move to using Sharp in CDN we've lost support for output of GIF images. We can use GIF as input, and convert to JPG or PNG, but we can't output a GIF.

One solution maybe to output the raw data from Sharp and pipe it into a GIF encoder, such as 
https://www.npmjs.com/package/gifencoder

**Comment by jimlambie** [comment]
Although the linked package might install node-canvas, which we might want to avoid.

**Comment by abovebored** [comment]
Would be cool to see:

* ability to convert to a `gifv` (essential a H.264 version) ([more info](https://help.imgur.com/hc/en-us/articles/208606616-What-is-GIFV-))
* select a 'poster frame' when converting from a GIF to a static format such as JPG

**Comment by adamkdean** [comment]
There have also been requests to crop gifs.

**Comment by jimlambie** [comment]
https://www.npmjs.com/package/animated-gif-detector
