### ISSUE TITLE
RGB colour profile issue

### ISSUE THREAD

**Issue by abovedave** [dadi/cdn#258]
Passing #e74521, getting back #e9430e

![](https://cdn.somedomain.tech/layout/c:e74521,h_100,w_100,x_0,y_0%7Co:output.jpg,h_100,w_100)

`https://cdn.somedomain.tech/layout/c:e74521,h_100,w_100,x_0,y_0%7Co:output.jpg,h_100,w_100`

**Comment by jimlambie** [comment]
@abovebored could be related to quality setting?

for e.g.

https://cdn.looksgre.at/https://looksgre.at/assets/img/placeholder.jpg?w=425&ratio=1-1&gravity=center&q=100
https://cdn.looksgre.at/https://looksgre.at/assets/img/placeholder.jpg?w=425&ratio=1-1&gravity=center&q=80
https://cdn.looksgre.at/https://looksgre.at/assets/img/placeholder.jpg?w=425&ratio=1-1&gravity=center&q=50
https://cdn.looksgre.at/https://looksgre.at/assets/img/placeholder.jpg?w=425&ratio=1-1&gravity=center&q=20

**Comment by abovebored** [comment]
Might well be. Note, I switched my example to png format and it's fine:

![](https://cdn.somedomain.tech/layout/c:e74521,h_100,w_100,x_0,y_0%7Co:output.png,h_100,w_100)

**Comment by eduardoboucas** [comment]
Hey fellas, is this still an issue?

**Comment by eduardoboucas** [comment]
👴
