### ISSUE TITLE
Image fallback not returned when crop is present

### ISSUE THREAD

**Issue by mingard** [dadi/cdn#282]
## Expected behaviour

A fallback image should be returned where the requested resource is invalid and a fallback is present in the FS and config.

## Actual behaviour

When requesting a missing image, the app returns the fallback, however if the crop param is passed with the request, an empty JSON object is returned.

## Steps to reproduce

- Set a fallback image in CDN
- Request a missing image
- Observer: the fallback is displayed
- Add a crop param e.g. `?crop=0,1,200,300`
- Observe: the fallback is no longer returned. Instead, an empty JSON object `{}` renders.

**Comment by eduardoboucas** [comment]
How exactly should we handle this? I assume we want to return the fallback image with the same dimensions determined by the crop, which is what the user is expecting. But blindly cropping the fallback image using the same coordinates as the original image will most likely result in a poor result.

Should we take the fallback image and do an `aspectfill` crop from the centre?

**Comment by mingard** [comment]
Yes I think that makes sense.
