### ISSUE TITLE
Output image has wrong dimensions when over the configured limit

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/cdn#283]
The image attached gets the wrong dimensions (357px wide) when using a query like `?width=900&resizeStyle=aspectfit`. This happens when the original image exceeds the maximum dimensions configured in CDN.

![owned-infrastructure](https://user-images.githubusercontent.com/4162329/32657288-1d8b8c04-c60d-11e7-9a7b-5c4cdafaa341.jpg)

**Comment by jimlambie** [comment]
From the looks of it, we only get the final dimensions correct if a ratio has been specified. 

In the case of no ratio being specified, I suggest we calculate it from the original imageInfo object, before continuing to determine the correct output dimensions:

The below would replace the lines at https://github.com/dadi/cdn/blob/develop/dadi/lib/handlers/image.js#L796-L811

```
  // get original image ratio, or use the specified one
  let ratio

  if (options.ratio) {
    ratio = options.ratio.split('-')
  } else {
    if (imageInfo.width > imageInfo.height) {
      ratio = [imageInfo.width/imageInfo.height, '1']
    } else {
      ratio = ['1', imageInfo.height/imageInfo.width]
    }
  }
```

**Comment by adamkdean** [comment]
I will take a look at this soon
