### ISSUE TITLE
Combining url params with req params causes 404

### ISSUE THREAD

**Issue by mingard** [dadi/cdn#284]
## Expected behaviour

Using path-based props e.g. `jpg/100/0/0/600/350/0/0/0/0/0/0/0/image.jpg` should either allow or ignore request params e.g. `jpg/100/0/0/600/350/0/0/0/0/0/0/0/image.jpg?q=70`

## Actual behaviour

404 is returned `{"statusCode":404}`

My preference would be to override the path props.

**Comment by jimlambie** [comment]
@mingard this isn't something we'll spend any time on. There are two URL formats in place, a legacy one and a modern, more robust one. If it was my decision to make, we'd ditch the legacy one and only use querystring parameters.

To make the above work with the specified quality parameter, you'll have to modify the path to the following: `jpg/70/0/0/600/350/0/0/0/0/0/0/0/image.jpg`

**Comment by mingard** [comment]
@jimlambie I agree that the legacy format should go. It’s currently still an issue for a project in production, so I’m leaving This open until it can be fixed there. These are hard coded urls which I’m working to remove.

**Comment by jimlambie** [comment]
The legacy URL format will be deprecated in CDN 2.0, and removed in CDN 3.0

**Comment by eduardoboucas** [comment]
Legacy URL has indeed been deprecated in the upcoming release of CDN. Should we close this?

**Comment by jimlambie** [comment]
@eduardoboucas agreed
