### ISSUE TITLE
Deprecate legacy URL format

### ISSUE THREAD

**Issue by jimlambie** [dadi/cdn#285]
In CDN 3.0 the legacy URL format will be removed. When 2.0 is published, requests using this format should cause a deprecation message to be displayed - perhaps with an example of the new format using the supplied parameters.

An additional message should be displayed at startup.

**Comment by eduardoboucas** [comment]
Closed in https://github.com/dadi/cdn/commit/24b990eedaee7f11845cd1979729f86bce0aee91.
