### ISSUE TITLE
JSON responses are not cached

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/cdn#291]
According to [this](https://github.com/dadi/cdn/blob/develop/dadi/lib/handlers/image.js#L177-L182), cached images are not used if the output is JSON. Unless there's a reason for this that I'm missing, we should be able to cache JSON responses in the same way we cache image streams.

What do you think @jimlambie?

**Comment by jimlambie** [comment]
I agree 100% - there are a couple of things we should revisit in the caching space for CDN.
