### ISSUE TITLE
Block origin access

### ISSUE THREAD

**Issue by mingard** [dadi/cdn#30]
Media can have `origin-block` boolean which when `true` blocks CDN from outputting the original file. Especially useful when working with large images or where licensing is granted based on maximum usable resolution. 

Suggest this is stored in CDN db rather than using AWS permissions to avoid reliance on third-party

**Comment by jimlambie** [comment]
No movement in over 12 months, closing. Please reopen if still required.

**Comment by mingard** [comment]
@jimlambie fine to close. This is covered in the output height and width limitations right?
