### ISSUE TITLE
Review config properties that can be overridden at domain level

### ISSUE THREAD

**Issue by jimlambie** [dadi/cdn#322]

**Comment by jimlambie** [comment]
@eduardoboucas 

```
aws.accessKeyId
aws.secretAccessKey
aws.region
notFound.statusCode
notFound.images.enabled
notFound.images.path
images.directory.enabled
images.directory.path
images.s3.enabled
images.s3.accessKey
images.s3.secretKey
images.s3.bucketName
images.s3.region
images.s3.endpoint
images.remote.enabled
images.remote.path
images.remote.allowFullURL
assets.directory.enabled
assets.directory.path
assets.s3.enabled
assets.s3.accessKey
assets.s3.secretKey
assets.s3.bucketName
assets.s3.region
assets.s3.endpoint
assets.remote.enabled
assets.remote.path
caching.expireAt
caching.ttl
status.enabled
status.requireAuthentication
status.standalone
status.port
status.routes
security.maxWidth
security.maxHeight
auth.tokenUrl
auth.clientId
auth.secret
auth.tokenTtl
auth.privateKey
cloudfront.enabled
cloudfront.accessKey
cloudfront.secretKey
cloudfront.distribution
gzip
headers.cacheControl
robots
engines.sharp.kernel
engines.sharp.interpolator
engines.sharp.centreSampling
experimental.jsTranspiling
```

**Comment by eduardoboucas** [comment]
To-do list for tracking progress:

- [ ] `aws.accessKeyId`
- [ ] `aws.secretAccessKey`
- [ ] `aws.region`
- [ ] `notFound.statusCode`
- [ ] `notFound.images.enabled`
- [ ] `notFound.images.path`
- [ ] `images.remote.enabled`
- [ ] `images.remote.path`
- [ ] `images.remote.allowFullURL`
- [ ] `assets.remote.enabled`
- [ ] `assets.remote.path`
- [ ] `caching.expireAt`
- [ ] `caching.ttl`
- [ ] `security.maxWidth`
- [ ] `security.maxHeight`
- [ ] `auth.clientId`
- [ ] `auth.secret`
- [ ] `auth.privateKey`
- [ ] `gzip`
- [ ] `headers.cacheControl`
- [ ] `engines.sharp.kernel`
- [ ] `engines.sharp.interpolator`
- [ ] `engines.sharp.centreSampling`
- [ ] `experimental.jsTranspiling`
