### ISSUE TITLE
{"message":"Cannot read property 'split' of null"}

### ISSUE THREAD

**Issue by sharipovmarat** [dadi/cdn#334]
```
$ curl http://127.0.0.1:8001/image.jpg
{"message":"Cannot read property 'split' of null"}
```
```
$ cat config/config.production.json
{
  "server": {
    "host": "0.0.0.0",
    "port": 8001
  },
  "images": {
    "directory": {
      "enabled": true,
      "path": "./images"
    }
  }
}
```

```
$ nodejs -v
v6.14.1

$ npm -v
5.6.0
```

Cannot install DadiCdn on my server
using https://docs.dadi.tech/cdn#installation this instruction

**Comment by jimlambie** [comment]
Hi @sharipovmarat, thanks for the issue. I'm unsure which instructions you refer to, as I have just installed CDN and used your supplied configuration without an error.

For reference, I am using Node 6.14.1, NPM 5.8.0 on  Mac OSX High Sierra

```
cd ~
mkdir cdn-test
cd cdn-test
npm init -y
npm install @dadi/cdn
```

Add an entry point, `index.js`:
```
require('@dadi/cdn')
```


```
NODE_ENV=production node index.js
```

**Comment by jimlambie** [comment]
Hi @sharipovmarat, thanks for the issue. I'm unsure which instructions you refer to, as I have just installed CDN and used your supplied configuration without an error.

For reference, I am using Node 6.14.1, NPM 5.8.0 on  Mac OSX High Sierra

```
cd ~
mkdir cdn-test
cd cdn-test
npm init -y
npm install @dadi/cdn
mkdir config
mkdir images
```

Add an entry point, `index.js`:
```
require('@dadi/cdn')
```

Create new config file, `config/config.production.json`, using your config above
Add `image.jpg` to the `images` directory

Run CDN:
```
NODE_ENV=production node index.js
```

**Comment by sharipovmarat** [comment]
I've solved my problem. Reinstalled nodejs via NVM and installed python3.6. Before i've used DigitalOcean OneClickApp's NodeJs. Thx
