### ISSUE TITLE
Upload image to CDN

### ISSUE THREAD

**Issue by sharipovmarat** [dadi/cdn#350]
"upload": {
    "enabled": true,
    "requireAuthentication": true,
    "pathFormat": "sha1/4"
  },

In configuration settings found this config. But not found documentation. Can you explain how to upload images to CDN?

**Comment by jimlambie** [comment]
Hi @sharipovmarat,

The file upload function in CDN was recently removed, for a number of reasons. It was a very naive implementation and didn't cover all of our built-in storage options. We ultimately came to the conclusion that CDN should remain a delivery tool - how a user gets their assets to their storage location for CDN to serve should be up to them. There are a great number of ways to do that, such as FTP, rsync, AWS client libraries - we didn't feel there needed to be anything in the core product that made such decsions on behalf of users.

If you need any further assistance in moving assets to your chosen storage location, we'd be happy to help!

**Comment by jimlambie** [comment]
Responded and closing. Please reopen if you'd like some assistance with this in the future!
