### ISSUE TITLE
Compression and encoding header applied to video files

### ISSUE THREAD

**Issue by jimlambie** [dadi/cdn#368]
_I caveat this issue with the assumption that the latest version of CDN can technically serve any type of file._

CDN is attempting to gzip video/mp4 and returning a response with the header `Content-Encoding: gzip` even though it hasn't actually compressed it.

This results in an error in Chrome (ERR_CONTENT_DECODING_FAILED) and the video doesn't play. Safari also fails to decode the response. Firefox is more forgiving and ignores the encoding header.

I have made some changes to the controller to ignore video/mp4 and can show that by not attempting the gzip step, the video loads and plays in Chrome. There still seems to be an issue with loading in Safari.

@eduardoboucas perhaps we should take a view on the types of content we gzip? Something along the lines of https://www.npmjs.com/package/compressible could be a useful resource to determine what is/not compressed.

Version: CDN 3.0
Browsers: Chrome, Safari (Firefox ignores issue)

**Comment by eduardoboucas** [comment]
I agree! That package seems like a sensible way to determine what should be compressed.

**Comment by abovedave** [comment]
We use this in Web, works well 👍

**Comment by abovedave** [comment]
The Safari issue is the requirement for range headers https://github.com/dadi/web/pull/354

**Comment by jimlambie** [comment]
Closed via https://github.com/dadi/cdn/pull/372
