### ISSUE TITLE
Support progressive JPEGs

### ISSUE THREAD

**Issue by abovedave** [dadi/cdn#378]
https://www.wired.com/2013/01/the-return-of-the-progressive-jpeg/

**Comment by jimlambie** [comment]
@abovedave I see Google's mod_pagespeed has a filter that does this:

https://www.modpagespeed.com/doc/reference-image-optimize#convert_jpeg_to_progressive

Good resource: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/automating-image-optimization/

A good option: https://www.npmjs.com/package/imagemin
