### ISSUE TITLE
Signed URLs for retrieving assets

### ISSUE THREAD

**Issue by abovedave** [dadi/cdn#382]

**Comment by jimlambie** [comment]
No information here... what's the use case?

**Comment by abovedave** [comment]
Securing dynamic CDN URLs so a bad actors cannot alter variables.

**Comment by jimlambie** [comment]
Like Keanu Reeves?

**Comment by abovedave** [comment]
![a2kybi2](https://user-images.githubusercontent.com/649231/42560714-40d38bac-84ef-11e8-9a76-3b3a2f66d1c6.gif)
