### ISSUE TITLE
Not able to install dadi/cdn

### ISSUE THREAD

**Issue by steefaan** [dadi/cdn#395]
If I run `dadi cdn new dadi-cdn` as described in the docs I get the following error message.

![image](https://user-images.githubusercontent.com/5982785/42116808-583bc0e2-7bf9-11e8-8437-c4b919010c4c.png)

If I rename `config/config.development.json.sample` to `config.development.json` and execute the command before again I get the following error message:

![image](https://user-images.githubusercontent.com/5982785/42116861-a402fe5a-7bf9-11e8-959e-d2c7aa3a1f1c.png)

**Comment by jimlambie** [comment]
Thanks @steefaan, I'll investigate what's happening here and get back to you as soon as I can

**Comment by eduardoboucas** [comment]
This should now be fixed.
