### ISSUE TITLE
Unexpected response from incomplete url

### ISSUE THREAD

**Issue by mingard** [dadi/cdn#406]
When there is a `notFound` image set and an incomplete url e.g. `/path/to/image` rather than `/path/to/image/foo.jpg`, a text/html response is returned but with the body of the `notFound` image. 

The expected response would be the same JSON formatted message expected when `notFound` is not set.

Tested with: 
```json
 "notFound": {
    "statusCode": 410,
    "images": {
      "enabled": true,
      "path": "./images/missing.png"
    }
  }
```

**Comment by jimlambie** [comment]
Closed via https://github.com/dadi/cdn/commit/55754dc9fe90f7d40b57b19f4a2770712c1fa969
