### ISSUE TITLE
Wrong assets path 

### ISSUE THREAD

**Issue by bnqtoan** [dadi/cdn#412]
Hello,

I'm trying to load this file http://thegioicuanang.com/wp-includes/css/dashicons.min.css via http://cdn.thegioicuanang.com/wp-includes/css/dashicons.min.css but the url is always wrong.

`{"message":"Not Found: http://thegioicuanang.com/ncludes/css/dashicons.min.css","statusCode":404,"success":false}`

This is my config file https://codebeautify.org/jsonviewer/cb0883a4

**Comment by jimlambie** [comment]
Hi @bnqtoan, thanks for the issue report. I'll look into this today

**Comment by jimlambie** [comment]
@bnqtoan this is fixed by #414, and released as CDN 3.2.1
