### ISSUE TITLE
Gif images issue 

### ISSUE THREAD

**Issue by mohit125** [dadi/cdn#458]
The following gif image(i have tried with other gifs as well) does not work when processed via cdn
https://media.giphy.com/media/3oKIPvQWkVBKRkPYJy/giphy.gif
it display a static image 
i tried searching but don't see a different option for gif image

**Comment by jimlambie** [comment]
Hi @mohit125 

CDN doesn't support serving animated GIFs yet - you will get the first frame from an animated GIF. This feature is on the roadmap, however - it is an often-requested feature!
