### ISSUE TITLE
Add support for content aware crop generation

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/cdn#48]
I've been playing with [smartcrop.js](https://github.com/jwagner/smartcrop.js/), an algorithm that, given an image and dimensions for a crop, uses image processing to find good crops automatically. 

It currently supports Sharp and Image Magick as image operation processors, but I've created an [adapter module for lwip](https://github.com/eduardoboucas/smartcrop-lwip), looking to integrate it with CDN.

I see this being useful in two ways:

1. A mode for getting an automatically cropped image, for when we want to display an image in various aspect ratios but don't have human-generated crops;

1. A mode for getting the coordinates of the best crop (by requesting a response in JSON format), to be used as a default or suggested crop in a crop editing tool.

This [test suite](http://29a.ch/sandbox/2014/smartcrop/examples/testsuite.html) shows the algorithm selecting crops for over 100 images, and this [test bed](https://29a.ch/sandbox/2014/smartcrop/examples/testbed.html) shows a live preview with any uploaded images.

If we're happy with this, I can look into the integration with CDN soon.

**Comment by jimlambie** [comment]
Closed by #50
