### ISSUE TITLE
Wrong bucket name used when image contains the string `s3`

### ISSUE THREAD

**Issue by fra967** [dadi/cdn#481]
CDN version 1.13.3

If an image filename contains the `s3` string and CDN is fetching images from a S3 bucket, the name of the bucket is wrongly changed and it results in a 403 error

This is probably due to the check made on `s3` (instead of `/s3`) in these lines
https://github.com/dadi/cdn/blob/v1.13.3/dadi/lib/storage/s3.js#L25
https://github.com/dadi/cdn/blob/v1.13.3/dadi/lib/storage/s3.js#L35

**Comment by jimlambie** [comment]
Closed via version https://github.com/dadi/cdn/tree/v1.14.0
